version: '2'
services:
  ssserver:
    build: .
    image: ssserver
    restart: always
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    environment:
      - LOCAL_PORT=8388
      - PASSWD=test
      - ENCRYPT_METHOD=aes-256-cfb
      - TIMEOUT=400
