#! /bin/bash
for VARIABLE in LOCAL_PORT ENCRYPT_METHOD PASSWD TIMEOUT;
do
  if [[ -z ${!VARIABLE} ]]; then
    echo "Error: $VARIABLE is not defined, please check your docker-compose.yml"
    exit
  fi
done
ss-server -s 0.0.0.0 -p $LOCAL_PORT -m $ENCRYPT_METHOD -k $PASSWD -t $TIMEOUT --fast-open
